/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.beandev.eventstore.app;

import io.beandev.eventstore.app.services.SmartContractService;
import io.beandev.eventstore.list.LinkedList;

import io.helidon.config.Config;
import io.helidon.webserver.WebServer;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        Config config = Config.create();
        WebServer.builder()
                .config(config.get("server"))
                .routing(it -> it.register("/sc", new SmartContractService()))

                .build()
                .start()
        ;
    }
}
